Need socat for IPv4/dualstack, because docker is brain dead. Added "set -x" to dind-cluster.sh for visibility during debug.

diff --git a/image/dindnet b/image/dindnet
--- a/image/dindnet
+++ b/image/dindnet
@@ -195,4 +195,20 @@ if [[ $IP_MODE = "ipv6" ]]; then
   sed "s/^nameserver.*127\.0\.0\.11/# Removed 127.0.0.1/" /etc/resolv.conf >/etc/resolv.conf.updated
   cp /etc/resolv.conf /etc/resolv.conf.orig
   cat /etc/resolv.conf.updated >/etc/resolv.conf
+else
+  # make docker's kube-dns friendly
+  old_ns="$(awk '/^nameserver/ {print $2; exit}' /etc/resolv.conf)"
+  if [[ ${old_ns} ]]; then
+    # sed -i doesn't work here because of docker's handling of /etc/resolv.conf
+    sed "s/^nameserver.*/nameserver ${IP}/" /etc/resolv.conf >/etc/resolv.conf.updated
+    cp /etc/resolv.conf /etc/resolv.conf.orig
+    cat /etc/resolv.conf.updated >/etc/resolv.conf
+    while true; do
+      socat udp4-recvfrom:53,reuseaddr,fork,bind=${IP} UDP:${old_ns}:53 || true
+      echo "WARNING: restarting socat" >&2
+    done
+  else
+    echo "WARNING: couldn't get nameserver" >&2
+    exit 1
+  fi
 fi
